"""Ribbon File Manager.

A cross-platform file manager with a Windows-Explorer-like Ribbon UI,
implemented with PyGObject (GTK3).

License: Apache-2.0
"""

__all__ = ["__version__"]

try:
    # Generated by setuptools_scm from the git tag (e.g. v1.6 -> 1.6).
    from ._version import __version__  # type: ignore
except Exception:  # noqa: BLE001 - installed without scm / no tag present
    try:
        from importlib.metadata import version as _pkg_version

        __version__ = _pkg_version("ribbonfm")
    except Exception:  # noqa: BLE001
        __version__ = "0.0.0"

